name: Build

on:
  release:
    types:
      - created

jobs:
  check-release:
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install --no-dev
          rm -rf vendor/ -R

      - name: Change permissions for release.sh
        run: chmod 755 .github/workflows/release.sh

      - name: Create Release Assets
        id: create_artifact
        run: |
          FILE_NAME=bitpay-checkout-for-woocommerce
          mkdir /home/runner/work/release
          cd $GITHUB_WORKSPACE
          zip -r /home/runner/work/release/${FILE_NAME}.zip ./* > /dev/null
          tar -czvf /home/runner/work/release/${FILE_NAME}.tar.gz ./* > /dev/null
        shell: bash

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} /home/runner/work/release/*

      - name: Copy the files directory with the Git repository to a new subversion tag
        env:
          SLUG: bitpay-checkout-for-woocommerce
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        run: $GITHUB_WORKSPACE/.github/workflows/release.sh
        shell: bash
