name: Build

on:
  release:
    types:
      - created

jobs:
  check-release:
    runs-on: ubuntu-20.04
    outputs:
      artifact_name: ${{ steps.create_artifact.outputs.artifact_name }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install --no-dev
          rm -rf vendor/ -R
          rm -rf .git/ -R

      - name: Change permissions for release.sh
        run: chmod 755 .github/workflows/release.sh

      - name: Create Release Artifact
        id: create_artifact
        run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION#refs/tags/}
          mkdir /home/runner/work/release
          zip -r /home/runner/work/release/test.zip $GITHUB_WORKSPACE > /dev/null
          echo "{artifact_name}=${VERSION}.zip" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check artifact
        run: ls -lha /home/runner/work/release
        shell: bash

      - name: Check name
        run: echo ${{ steps.create_artifact.outputs.artifact_name }}
        shell: bash

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.create_artifact.outputs.artifact_name }}
          path: /home/runner/work/release/test.zip
          if-no-files-found: error

      - name: Copy the files directory with the Git repository to a new subversion tag
        env:
          SLUG: bitpay-checkout-for-woocommerce
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        run: $GITHUB_WORKSPACE/.github/workflows/release.sh
        shell: bash
